version: '3'
services:
  experiments:
    runtime: nvidia
    env_file: .env
    build:
      context: ..
      dockerfile: config/Dockerfile
      args:
        base_image: $IMAGE_BASE
        jupyter_theme: $JUPYTER_THEME
    image: $IMAGE
    mem_limit: 12g
    ports:
      - 8888:8888
      - 6006:6006
    volumes:
      - ../notebooks:/tf
      - ../data:/data
      - ../data/cached/keras:/root/.keras
      - ../data/cached/tfds:/root/tensorflow_datasets
      - ../logs:/tf/logs
      - ../datasets:/tf/datasets
      - ../secrets/kaggle:/root/.kaggle
